name: Continuous Integration 
on: 
    push: 
      branches: [ "main"]
    pull_request:
      branches: [ "main" ]
    workflow_dispatch:
    
jobs: 
  build: 
     runs-on: ubuntu-latest
     container: docker:/dvcorg/cml-py3:latest
     steps:
        - uses: actions/checkout@v3
        - name: iterative/setup-cml@v2
        - uses: actions/setup-node@v4
        - name: Install Packeges
        - run: make install
        - name: Format
        - run: make format
        - name: Train
        - run: make train
        - name: Evaluation
          env: 
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: make eval
          
        
        
     
